---
- name: Verificar versión de Java
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Obtener version java
      shell: java -version
      ignore_errors: true
      register: resultado
    
    - name: Instalar Java si no está presente
      apt:
        name: openjdk-11-jdk   # Reemplaza con el paquete adecuado para tu sistema
        state: present
      when: resultado.rc != 0

    - name: Mostrar versión de Java instalada
      shell: java -version
      register: resultado
      changed_when: false
      failed_when: false


    - name: visualizar resultado 
      debug: var=resultado.stderr_lines[0]
