---
- name: Actualizar base de datos PostgreSQL en Red Hat Enterprise Linux
  hosts: tu_servidor
  become: true
  tasks:

    - name: Detener el servicio de PostgreSQL
      systemd:
        name: postgresql
        state: stopped

    - name: Realizar copia de seguridad de la base de datos
      shell: pg_dumpall -U postgres -f /ruta/copia_seguridad.sql
      args:
        executable: /bin/bash
      register: copia_seguridad
      changed_when: copia_seguridad.stdout != ''

    - name: Actualizar el sistema operativo
      yum:
        name: '*'
        state: latest
      register: sistema_actualizado
      changed_when: sistema_actualizado.changed

    - name: Actualizar el paquete de PostgreSQL
      yum:
        name: postgresql
        state: latest
      register: postgres_actualizado
      changed_when: postgres_actualizado.changed

    - name: Iniciar el servicio de PostgreSQL
      systemd:
        name: postgresql
        state: started

    - name: Verificar el estado de la base de datos
      command: psql -U postgres -c 'SELECT version();'
      register: estado_bd

    - name: Mostrar estado de la base de datos
      debug:
        var: estado_bd.stdout

